import React from 'react';
import { Download, Printer } from 'lucide-react';
import { formatCurrency } from '../../../utils/formatters';

const ReportsTab = ({ reports }) => {
    return (
        <div className="reports-content">
            <div className="reports-grid">
                {reports.map(report => (
                    <div key={report.id} className="report-card">
                        <div className="report-header">
                            <div className="report-title">
                                <h4>{report.title}</h4>
                                <span className="report-period">{report.period}</span>
                            </div>
                            <div className="report-actions">
                                <button className="btn-icon">
                                    <Download size={16} />
                                </button>
                                <button className="btn-icon">
                                    <Printer size={16} />
                                </button>
                            </div>
                        </div>
                        <div className="report-body">
                            <div className="report-stats">
                                <div className="report-stat">
                                    <span className="label">Collected:</span>
                                    <span className="value collected">
                                        {formatCurrency(report.totalCollected)}
                                    </span>
                                </div>
                                <div className="report-stat">
                                    <span className="label">Pending:</span>
                                    <span className="value pending">
                                        {formatCurrency(report.totalPending)}
                                    </span>
                                </div>
                                <div className="report-stat">
                                    <span className="label">Rate:</span>
                                    <span className="value rate">{report.collectionRate}%</span>
                                </div>
                            </div>
                            {report.gradeBreakdown && (
                                <div className="breakdown-section">
                                    <h5>Grade-wise Breakdown</h5>
                                    <div className="breakdown-list">
                                        {report.gradeBreakdown.map((item, index) => (
                                            <div key={index} className="breakdown-item">
                                                <span>Grade {item.grade}</span>
                                                <div className="breakdown-values">
                                                    <span>{formatCurrency(item.collected || item.overdue)}</span>
                                                    {item.pending && (
                                                        <span className="pending-small">
                                                            Pending: {formatCurrency(item.pending)}
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                            {report.feeTypeBreakdown && (
                                <div className="breakdown-section">
                                    <h5>Fee Type Breakdown</h5>
                                    <div className="breakdown-list">
                                        {report.feeTypeBreakdown.map((item, index) => (
                                            <div key={index} className="breakdown-item">
                                                <span>{item.type}</span>
                                                <span>{formatCurrency(item.amount)}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                        <div className="report-footer">
                            <div className="report-meta">
                                <span>Generated by: {report.generatedBy}</span>
                                <span>Date: {report.generatedAt.split(' ')[0]}</span>
                            </div>
                            <button className="btn btn-secondary btn-sm">
                                View Full Report
                            </button>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default ReportsTab;
